name: Build and Deploy Document
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  build-document:
    name: Build Document
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v6.0.0

      - name: Compile Document
        uses: xu-cheng/latex-action@4.0.0
        with:
          root_file: main.tex
          texlive_version: 2025
          args: -pdf -bibtex

      - name: Rename document
        run: mkdir dist && mv main.pdf dist/buku-kp.pdf

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: dist

  deploy-pages:
    name: Deploy Pages
    needs: build-document
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    concurrency:
      group: pages
      cancel-in-progress: false
    steps:
      - name: Configure Pages
        uses: actions/configure-pages@v5.0.0
        
      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
